//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShop.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiftShop.Application.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email address is required..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field shouldn&apos;t be empty.
        /// </summary>
        public static string FieldEmptyValidation {
            get {
                return ResourceManager.GetString("FieldEmptyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered &apos;{0}&apos; field&quot;.
        /// </summary>
        public static string FieldNullValidation {
            get {
                return ResourceManager.GetString("FieldNullValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found in the request.
        /// </summary>
        public static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID entered not valid.
        /// </summary>
        public static string GuidIdNoValid {
            get {
                return ResourceManager.GetString("GuidIdNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value must be greater than {1}.
        /// </summary>
        public static string IntGreaterThanValidation {
            get {
                return ResourceManager.GetString("IntGreaterThanValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file length, seems to be empty.
        /// </summary>
        public static string InvalidFileLength {
            get {
                return ResourceManager.GetString("InvalidFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} characters exceeded.
        /// </summary>
        public static string MaxLengthValidation {
            get {
                return ResourceManager.GetString("MaxLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload more than one file at the time.
        /// </summary>
        public static string NotUploadMore1File {
            get {
                return ResourceManager.GetString("NotUploadMore1File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one lowercase letter.
        /// </summary>
        public static string PasswordLowercaseValidation {
            get {
                return ResourceManager.GetString("PasswordLowercaseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password length must not exceed {0}.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password length must be at least {0}.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one {0}.
        /// </summary>
        public static string PasswordNonAlphanumericValidation {
            get {
                return ResourceManager.GetString("PasswordNonAlphanumericValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one number.
        /// </summary>
        public static string PasswordNumberValidation {
            get {
                return ResourceManager.GetString("PasswordNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password don´t match.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one uppercase letter.
        /// </summary>
        public static string PasswordUppercaseValidation {
            get {
                return ResourceManager.GetString("PasswordUppercaseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not deleted successfully.
        /// </summary>
        public static string ProductNotDeleted {
            get {
                return ResourceManager.GetString("ProductNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
